### ISSUE TITLE
[Bug]: The citation style APA always gets `CiteprocRsKit.CRError`

### ISSUE THREAD

**Issue by twio142** [zeitlings/ubib#1]
### What happened?

No matter which variation of APA, it always get the error:

```
Failed to get Citation with style 'apa' with error: The operation couldn’t be completed. (CiteprocRsKit.CRError error 1.)
```

While it work with other styles (chicago, ama, mla, etc.) just fine.

### Which input causes the bug?

ubib \<url>

### Version

1.0.0

**Comment by zeitlings** [comment]
Hey @twio142 ,
This is a problem with citeproc-rs not handling some cases when parsing the citation style XML. APA was updated a few days ago and has been failing since. Others have encountered the same problem  [#156](https://github.com/zotero/citeproc-rs/issues/156). 

Using the [WASM demo of citeproc-rs](https://cormacrelf.github.io/citeproc-wasm-demo/), I found that the errors exposed the offending tokens. Simply removing them from the CSL should fix the problem. Here are the modified styles for APA 7th, 6th and 5th editions that work as expected on my end: [apa7+6+5.zip](https://github.com/zeitlings/ubib/files/11574386/apa7%2B6%2B5.zip). 

You can move them to the "data folder" where the workflow will pick up on them  (`ubib :c > Browse Data Folder > csl`)

**Comment by twio142** [comment]
It works. Thanks a lot!
